# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayReminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
