# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayReminder', '0003_auto_20160320_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
