# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayReminder', '0004_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=100)),
                ('patients_update_time', models.DateTimeField(default='1970-01-01')),
            ],
        ),
    ]
